const fs = require('fs');
const path = require('path');

const content = `key	en	en_US	en_CA	es	es_419	es_ES	fr	fr_CA	fr_FR	de	pt	it	ru
AgeGroupCodeAlreadyExists	This code and gender combination is already used by {0}	This code and gender combination is already used by {0}	This code and gender combination is already used by {0}	Esta combinación de código y género ya está siendo utilizada por {0}	Esta combinación de código y género ya está siendo utilizada por {0}	Esta combinación de código y género ya está siendo utilizada por {0}	Cette combinaison de code et de genre est déjà utilisée par {0}	Cette combinaison de code et de genre est déjà utilisée par {0}	Cette combinaison de code et de genre est déjà utilisée par {0}	Diese Kombination aus Code und Geschlecht wird bereits von {0} verwendet	Esta combinação de código e gênero já está sendo usada por {0}	Questa combinazione di codice e genere è già utilizzata da {0}	Эта комбинация кода и пола уже используется {0}
AgeGroup.DuplicateCodeGender	The Age Group definition for {0} creates a duplicate for {1} ( Gender {2} )	The Age Group definition for {0} creates a duplicate for {1} ( Gender {2} )	The Age Group definition for {0} creates a duplicate for {1} ( Gender {2} )	La definición del Grupo de Edad para {0} crea un duplicado para {1} ( Género {2} )	La definición del Grupo de Edad para {0} crea un duplicado para {1} ( Género {2} )	La definición del Grupo de Edad para {0} crea un duplicado para {1} ( Género {2} )	La définition du groupe d'âge pour {0} crée un doublon pour {1} ( Genre {2} )	La définition du groupe d'âge pour {0} crée un doublon pour {1} ( Genre {2} )	La définition du groupe d'âge pour {0} crée un doublon pour {1} ( Genre {2} )	Die Altersgruppen-Definition für {0} erstellt ein Duplikat für {1} ( Geschlecht {2} )	A definição de Grupo de Idade para {0} cria uma duplicata para {1} ( Gênero {2} )	La definizione del Gruppo di Età per {0} crea un duplicato per {1} ( Genere {2} )	Определение возрастной группы для {0} создает дубликат для {1} ( Пол {2} )
AgeGroup.CannotProcessCell	Cannot process content of cell {0} ({1})	Cannot process content of cell {0} ({1})	Cannot process content of cell {0} ({1})	No se puede procesar el contenido de la celda {0} ({1})	No se puede procesar el contenido de la celda {0} ({1})	No se puede procesar el contenido de la celda {0} ({1})	Impossible de traiter le contenu de la cellule {0} ({1})	Impossible de traiter le contenu de la cellule {0} ({1})	Impossible de traiter le contenu de la cellule {0} ({1})	Inhalt der Zelle {0} kann nicht verarbeitet werden ({1})	Não é possível processar o conteúdo da célula {0} ({1})	Impossibile elaborare il contenuto della cella {0} ({1})	Невозможно обработать содержимое ячейки {0} ({1})`;

const filePath = 'c:\\Users\\lamyj\\git\\owlcms4\\shared\\src\\main\\resources\\i18n\\agegroup_duplicate_errors.tsv';
fs.writeFileSync(filePath, content, 'utf8');
console.log('File written successfully');
