steps:
-  checkout: self
   submodules: recursive
# -  script: |
#      mkdir /tmp/downloads
#      mkdir $HOME/node
#      curl -fsSL https://nodejs.org/dist/v16.17.1/node-v16.17.1-linux-x64.tar.xz > /tmp/downloads/f.tar.xz
#      tar -xvf /tmp/downloads/f.tar.xz -C $HOME/node
#      cd $HOME/node/node-v16.17.1-linux-x64/bin
#      ./node --version
#      ./npm --version
#      cp ./node /usr/local/bin
#      cp ./npm /usr/local/bin
-  script: |
      mkdir $HOME/.m2
      cp src/main/azure-pipelines/settings.xml $HOME/.m2/settings.xml
-  task: MavenAuthenticate@0
   displayName: Populate settings.xml for deploy servers
   inputs:
      mavenServiceConnections: owlcms-maven-repo
-  task: Cache@2
   displayName: Cache Maven local repository
   inputs:
      key: '"maven20221011a" | $(Agent.OS)'
      path: $(MavenCacheFolder)
   env:
      VSO_DEDUP_REDIRECT_TIMEOUT_IN_SEC: 5
- task: Maven@3.205.1
  displayName: update revision property
  env:
    VSO_DEDUP_REDIRECT_TIMEOUT_IN_SEC: 5
  inputs:
    mavenPomFile: pom.xml
    mavenOptions: -Xmx3072m $(MavenOpts)
    javaHomeOption: JDKVersion
    jdkVersionOption: "1.11"
    jdkArchitectureOption: x64
    publishJUnitResults: false
    goals: -N $(MavenOpts) -Dmaven.test.skip=true -Dproperty=revision -DnewVersion=$(Revision) versions:set-property 