<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>app.owlcms</groupId>
        <artifactId>owlcms4top</artifactId>
        <version>4.9.0.1</version>
    </parent>

    <name>docker packaging</name>
    <description>Owlcms Docker Packaging</description>
    <artifactId>owlcms-docker</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>app.owlcms</groupId>
            <artifactId>owlcms</artifactId>
            <version>${project.version}</version>
        </dependency>
        		
		<!-- https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.0.0</version> <!--$NO-MVN-MAN-VER$-->
		</dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
                <executions>
                    <execution>
                        <id>copy-owlcms-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>app.owlcms</groupId>
                                    <artifactId>owlcms</artifactId>
                                    <version>${project.version}</version>
                                    <outputDirectory>${project.build.directory}/docker-context</outputDirectory>
                                    <destFileName>owlcms.jar</destFileName>
                                </artifactItem>
                            </artifactItems>
                            <overWriteIfNewer>true</overWriteIfNewer>
                            <overWriteReleases>true</overWriteReleases>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-logback-configuration</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/docker-context/classes</outputDirectory>
                            <overwrite>true</overwrite>
                            <resources>
                                <resource>
                                    <directory>${project.parent.basedir}/owlcms/src/main/resources</directory>
                                    <includes>
                                        <include>logback.xml</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>